### ISSUE TITLE
license?  

### ISSUE THREAD

**Issue by headupinclouds** [timnugent/kpca-eigen#1]
This looks like a nice class.  Does this have a license?

**Comment by timnugent** [comment]
Added GPLv3. Hope that's ok, let me know if not.

**Comment by headupinclouds** [comment]
Since you asked... I would need something like a BSD, MIT, or Apache style license to use it.  Of course I understand if you don't desire to support those.  Thanks.

**Comment by timnugent** [comment]
No problem, done.
